package com.actvn.qldiemhsthpt.ui;

import com.actvn.qldiemhsthpt.util.FileControl;
import com.actvn.qldiemhsthpt.ui.SapXepDiemHSForm;
import com.actvn.qldiemhsthpt.ui.LocDiemHocSinhForm;
import com.actvn.qldiemhsthpt.model.DiemTungMon;
import com.actvn.qldiemhsthpt.model.DiemCuaHS;
import com.actvn.qldiemhsthpt.model.HocSinh;
import static com.actvn.qldiemhsthpt.util.FileControl.JSON_DIEM_PATH;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class NhapDiemChoHocSinhForm extends javax.swing.JFrame {

    static List<DiemCuaHS> data;
    static int stt;
    static DefaultTableModel model;
    int selectedRowIndex;
    static List<HocSinh> datahs;
    String[] listMaHS;

    /**
     * Creates new form NhapDiemChoHocSinhForm
     */
    public NhapDiemChoHocSinhForm() {
        initComponents();
        stt = 1;
        data = FileControl.readJSONFile(JSON_DIEM_PATH);
        model = (DefaultTableModel) tblBangDiem.getModel();
        datahs = FileControl.readJSONFileTT(com.actvn.qldiemhsthpt.util.FileControl.JSON_THONGTIN_PATH);
        listMaHS = createStringListData(datahs);
        cbxMaHS.setModel(new DefaultComboBoxModel<>(listMaHS));
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxMaHS = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtToan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLy = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHoa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSinh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCongNghe = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNguVan = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        txtSu = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtGDCD = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnLamTrong = new javax.swing.JButton();
        btnSuaDiem = new javax.swing.JButton();
        btnXuatFileJSON = new javax.swing.JButton();
        btnSapXep = new javax.swing.JButton();
        btnLoc = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnquaylai = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangDiem = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BẢNG ĐIỂM CỦA HỌC SINH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel2.setText("Mã Học Sinh:");

        cbxMaHS.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        cbxMaHS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("Nhập Điểm Các Môn:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel4.setText("Toán:");

        txtToan.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel5.setText("Vật Lý:");

        txtLy.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel6.setText("Hoá Học:");

        txtHoa.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel7.setText("Sinh Học:");

        txtSinh.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel8.setText("Tin Học:");

        txtTin.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel9.setText("Công Nghệ:");

        txtCongNghe.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel10.setText("Ngữ Văn:");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel11.setText("Địa Lý:");

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel12.setText("Lịch Sử:");

        txtNguVan.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        txtDia.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        txtSu.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel13.setText("Giáo Dục Công Dân:");

        txtGDCD.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        btnThem.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLamTrong.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnLamTrong.setText("Làm Trống");
        btnLamTrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamTrongActionPerformed(evt);
            }
        });

        btnSuaDiem.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnSuaDiem.setText("Sửa Điểm");
        btnSuaDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDiemActionPerformed(evt);
            }
        });

        btnXuatFileJSON.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnXuatFileJSON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/actvn/quanlysv/images/Save.png"))); // NOI18N
        btnXuatFileJSON.setText("Xuất ra File JSON");
        btnXuatFileJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileJSONActionPerformed(evt);
            }
        });

        btnSapXep.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnSapXep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/actvn/quanlysv/images/Statistics.png"))); // NOI18N
        btnSapXep.setText("Sắp Xếp");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });

        btnLoc.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnLoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/actvn/quanlysv/images/Notes.png"))); // NOI18N
        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnquaylai.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnquaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/actvn/quanlysv/images/Refresh.png"))); // NOI18N
        btnquaylai.setText("Quay Lại");
        btnquaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquaylaiActionPerformed(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/actvn/quanlysv/images/Search.png"))); // NOI18N
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        txtTimKiem.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel14.setText("Nhập mã sinh viên cần tìm kiếm:");

        tblBangDiem.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tblBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã HS", "Toán", "Vật Lý", "Hoá Học", "Sinh Học", "Tin Học", "Công Nghệ", "Ngữ Văn", "Địa Lý", "Lịch Sử", "Giáo Dục Công Dân", "Điểm Trung Bình", "Học Lực"
            }
        ));
        tblBangDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangDiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBangDiem);

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel15.setText("Tìm Kiếm Điểm Của Học Sinh:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtToan, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLy, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtCongNghe, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtTin, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNguVan, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGDCD, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLamTrong, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSuaDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnTimKiem)
                        .addGap(50, 50, 50)
                        .addComponent(btnquaylai)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnXuatFileJSON, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(btnSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtNguVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCongNghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtSu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaDiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtGDCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXuatFileJSON, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnquaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static String[] createStringListData(List<HocSinh> datahs) {
        String[] mahs = new String[datahs.size()];
        for (int i = 0; i < datahs.size(); i++) {
            mahs[i] = datahs.get(i).getMaHS();
        }
        return mahs;
    }

    static void fillTable() {
        stt = 1;
        for (DiemCuaHS item : data) {
            DiemCuaHS hs = item;
            model.addRow(new Object[]{
                stt++,
                hs.getMaHS(),
                hs.getTatCaMon().get(0).getDiem_cac_mon(),
                hs.getTatCaMon().get(1).getDiem_cac_mon(),
                hs.getTatCaMon().get(2).getDiem_cac_mon(),
                hs.getTatCaMon().get(3).getDiem_cac_mon(),
                hs.getTatCaMon().get(4).getDiem_cac_mon(),
                hs.getTatCaMon().get(5).getDiem_cac_mon(),
                hs.getTatCaMon().get(6).getDiem_cac_mon(),
                hs.getTatCaMon().get(7).getDiem_cac_mon(),
                hs.getTatCaMon().get(8).getDiem_cac_mon(),
                hs.getTatCaMon().get(9).getDiem_cac_mon(),
                hs.getDiemTBmon(),
                hs.getHocLuc(),});
        }
    }

    private void fillToJTable() {
        if (data != null) {
            DiemCuaHS hs = data.get(data.size() - 1);
            model.addRow(new Object[]{
                stt++,
                hs.getMaHS(),
                hs.getTatCaMon().get(0).getDiem_cac_mon(),
                hs.getTatCaMon().get(1).getDiem_cac_mon(),
                hs.getTatCaMon().get(2).getDiem_cac_mon(),
                hs.getTatCaMon().get(3).getDiem_cac_mon(),
                hs.getTatCaMon().get(4).getDiem_cac_mon(),
                hs.getTatCaMon().get(5).getDiem_cac_mon(),
                hs.getTatCaMon().get(6).getDiem_cac_mon(),
                hs.getTatCaMon().get(7).getDiem_cac_mon(),
                hs.getTatCaMon().get(8).getDiem_cac_mon(),
                hs.getTatCaMon().get(9).getDiem_cac_mon(),
                hs.getDiemTBmon(),
                hs.getHocLuc(),});
        }
    }

    private boolean checkMaHS(String[] mahs, String s) {
        for (String item : mahs) {
            if (item.equals(s)) {
                return true;
            }
        }
        return false;
    }

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        try {
            String mahs = cbxMaHS.getSelectedItem().toString();
            List<DiemTungMon> TCM = new ArrayList<>();
            TCM.add(new DiemTungMon(Double.parseDouble(txtToan.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtLy.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtHoa.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtSinh.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtTin.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtCongNghe.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtNguVan.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtDia.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtSu.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtGDCD.getText())));

            DiemCuaHS dchs = new DiemCuaHS(mahs);
            dchs.setTatCaMon(TCM);

            if (checkMaHS(listMaHS, mahs)) {
                int ks = 0;
                for (DiemCuaHS item : data) {
                    if (item.getMaHS().equals(dchs.getMaHS())) {
                        JOptionPane.showMessageDialog(this, "Học Sinh Đã Tồn Tại", "CẢNH BÁO!!!", JOptionPane.ERROR_MESSAGE);
                        btnLamTrongActionPerformed(evt);
                        break;
                    } else {
                        ks++;
                    }
                }
                if (ks == data.size()) {
                    if (dchs.checkdiem()) {
                        data.add(dchs);
                        fillToJTable();
                        btnLamTrongActionPerformed(evt);
                    } else {
                        JOptionPane.showMessageDialog(this, "Điểm Không Hợp Lệ", "CẢNH BÁO!!!", JOptionPane.ERROR_MESSAGE);
                        btnLamTrongActionPerformed(evt);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Học Sinh Không Tồn Tại!!!", "CẢNH BÁO!!!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (java.lang.NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Định dạng không hợp lệ", "CẢNH BÁO!!!", JOptionPane.ERROR_MESSAGE);
            btnLamTrongActionPerformed(evt);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamTrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamTrongActionPerformed
        cbxMaHS.setSelectedIndex(0);
        txtToan.setText("");
        txtLy.setText("");
        txtHoa.setText("");
        txtSinh.setText("");
        txtTin.setText("");
        txtCongNghe.setText("");
        txtNguVan.setText("");
        txtDia.setText("");
        txtSu.setText("");
        txtGDCD.setText("");
    }//GEN-LAST:event_btnLamTrongActionPerformed

    private void btnSuaDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDiemActionPerformed
        try {
            String mahs = cbxMaHS.getSelectedItem().toString();
            List<DiemTungMon> TCM = new ArrayList<>();
            TCM.add(new DiemTungMon(Double.parseDouble(txtToan.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtLy.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtHoa.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtSinh.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtTin.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtCongNghe.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtNguVan.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtDia.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtSu.getText())));
            TCM.add(new DiemTungMon(Double.parseDouble(txtGDCD.getText())));

            DiemCuaHS dchs = new DiemCuaHS(mahs);
            data.set(selectedRowIndex, dchs);
            dchs.setTatCaMon(TCM);

            if (model.getValueAt(selectedRowIndex, 1).equals(dchs.getMaHS())) {
                if (dchs.checkdiem()) {
                    model.setValueAt(dchs.getTatCaMon().get(0).getDiem_cac_mon(), selectedRowIndex, 2);
                    model.setValueAt(dchs.getTatCaMon().get(1).getDiem_cac_mon(), selectedRowIndex, 3);
                    model.setValueAt(dchs.getTatCaMon().get(2).getDiem_cac_mon(), selectedRowIndex, 4);
                    model.setValueAt(dchs.getTatCaMon().get(3).getDiem_cac_mon(), selectedRowIndex, 5);
                    model.setValueAt(dchs.getTatCaMon().get(4).getDiem_cac_mon(), selectedRowIndex, 6);
                    model.setValueAt(dchs.getTatCaMon().get(5).getDiem_cac_mon(), selectedRowIndex, 7);
                    model.setValueAt(dchs.getTatCaMon().get(6).getDiem_cac_mon(), selectedRowIndex, 8);
                    model.setValueAt(dchs.getTatCaMon().get(7).getDiem_cac_mon(), selectedRowIndex, 9);
                    model.setValueAt(dchs.getTatCaMon().get(8).getDiem_cac_mon(), selectedRowIndex, 10);
                    model.setValueAt(dchs.getTatCaMon().get(9).getDiem_cac_mon(), selectedRowIndex, 11);
                    model.setValueAt(dchs.getDiemTBmon(), selectedRowIndex, 12);
                    model.setValueAt(dchs.getHocLuc(), selectedRowIndex, 13);
                    btnLamTrongActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(this, "Điểm Không Hợp Lệ", "CẢNH BÁO!!!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không Được Sửa Mã Sinh Viên", "CẢNH BÁO!!!", JOptionPane.ERROR_MESSAGE);
                cbxMaHS.setSelectedItem(model.getValueAt(selectedRowIndex, 1));
            }
        } catch (java.lang.NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Định dạng không hợp lệ", "CẢNH BÁO!!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaDiemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        MainMenu loc = new MainMenu();
        loc.setVisible(true);
        this.setVisible(false);
        loc.pack();
        loc.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowClosing

    private void btnquaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquaylaiActionPerformed
        txtTimKiem.setText("");
        TableRowSorter<DefaultTableModel> tk = new TableRowSorter<>(model);
        tblBangDiem.setRowSorter(tk);
        tk.setRowFilter(RowFilter.regexFilter(txtTimKiem.getText()));
    }//GEN-LAST:event_btnquaylaiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        TableRowSorter<DefaultTableModel> tk = new TableRowSorter<>(model);
        tblBangDiem.setRowSorter(tk);
        tk.setRowFilter(RowFilter.regexFilter(txtTimKiem.getText()));
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        btnXuatFileJSONActionPerformed(evt);
        data.remove(selectedRowIndex);
        model.setRowCount(0);
        fillTable();
        btnLamTrongActionPerformed(evt);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        btnXuatFileJSONActionPerformed(evt);
        LocDiemHocSinhForm loc = new LocDiemHocSinhForm();
        loc.setVisible(true);
        this.setVisible(false);
        loc.pack();
        loc.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnLocActionPerformed

    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        btnXuatFileJSONActionPerformed(evt);
        SapXepDiemHSForm sx = new SapXepDiemHSForm();
        sx.setVisible(true);
        this.setVisible(false);
        sx.pack();
        sx.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSapXepActionPerformed

    private void btnXuatFileJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileJSONActionPerformed
        FileControl.writeJSONFile(data, com.actvn.qldiemhsthpt.util.FileControl.JSON_DIEM_PATH);
    }//GEN-LAST:event_btnXuatFileJSONActionPerformed

    private void tblBangDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangDiemMouseClicked
        selectedRowIndex = tblBangDiem.getSelectedRow();
        DiemCuaHS hs = new DiemCuaHS();
        List<DiemTungMon> TCM = new ArrayList<>();
        hs.setMaHS(model.getValueAt(selectedRowIndex, 1).toString());
        TCM.add(new DiemTungMon(Double.valueOf(model.getValueAt(selectedRowIndex, 2).toString())));
        TCM.add(new DiemTungMon(Double.valueOf(model.getValueAt(selectedRowIndex, 3).toString())));
        TCM.add(new DiemTungMon(Double.valueOf(model.getValueAt(selectedRowIndex, 4).toString())));
        TCM.add(new DiemTungMon(Double.valueOf(model.getValueAt(selectedRowIndex, 5).toString())));
        TCM.add(new DiemTungMon(Double.valueOf(model.getValueAt(selectedRowIndex, 6).toString())));
        TCM.add(new DiemTungMon(Double.valueOf(model.getValueAt(selectedRowIndex, 7).toString())));
        TCM.add(new DiemTungMon(Double.valueOf(model.getValueAt(selectedRowIndex, 8).toString())));
        TCM.add(new DiemTungMon(Double.valueOf(model.getValueAt(selectedRowIndex, 9).toString())));
        TCM.add(new DiemTungMon(Double.valueOf(model.getValueAt(selectedRowIndex, 10).toString())));
        TCM.add(new DiemTungMon(Double.valueOf(model.getValueAt(selectedRowIndex, 11).toString())));
        hs.setTatCaMon(TCM);

        cbxMaHS.setSelectedItem(hs.getMaHS());
        txtToan.setText(String.valueOf(hs.getTatCaMon().get(0).getDiem_cac_mon()));
        txtLy.setText(String.valueOf(hs.getTatCaMon().get(1).getDiem_cac_mon()));
        txtHoa.setText(String.valueOf(hs.getTatCaMon().get(2).getDiem_cac_mon()));
        txtSinh.setText(String.valueOf(hs.getTatCaMon().get(3).getDiem_cac_mon()));
        txtTin.setText(String.valueOf(hs.getTatCaMon().get(4).getDiem_cac_mon()));
        txtCongNghe.setText(String.valueOf(hs.getTatCaMon().get(5).getDiem_cac_mon()));
        txtNguVan.setText(String.valueOf(hs.getTatCaMon().get(6).getDiem_cac_mon()));
        txtDia.setText(String.valueOf(hs.getTatCaMon().get(7).getDiem_cac_mon()));
        txtSu.setText(String.valueOf(hs.getTatCaMon().get(8).getDiem_cac_mon()));
        txtGDCD.setText(String.valueOf(hs.getTatCaMon().get(9).getDiem_cac_mon()));
    }//GEN-LAST:event_tblBangDiemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapDiemChoHocSinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapDiemChoHocSinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapDiemChoHocSinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapDiemChoHocSinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapDiemChoHocSinhForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamTrong;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnSuaDiem;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatFileJSON;
    private javax.swing.JButton btnquaylai;
    private javax.swing.JComboBox<String> cbxMaHS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblBangDiem;
    private javax.swing.JTextField txtCongNghe;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtGDCD;
    private javax.swing.JTextField txtHoa;
    private javax.swing.JTextField txtLy;
    private javax.swing.JTextField txtNguVan;
    private javax.swing.JTextField txtSinh;
    private javax.swing.JTextField txtSu;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTin;
    private javax.swing.JTextField txtToan;
    // End of variables declaration//GEN-END:variables
}
