package com.actvn.qldiemhsthpt.ui;

import com.actvn.qldiemhsthpt.util.FileControl;
import com.actvn.qldiemhsthpt.model.DiemCuaHSController;
import com.actvn.qldiemhsthpt.model.DiemCuaHS;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class SapXepDiemHSForm extends javax.swing.JFrame {

    List<DiemCuaHS> data, subList;
    DefaultTableModel model;
    DiemCuaHS diemcuahs;

    /**
     * Creates new form SapXepDiemHSForm
     */
    public SapXepDiemHSForm() {
        initComponents();
        data = FileControl.readJSONFile(com.actvn.qldiemhsthpt.util.FileControl.JSON_DIEM_PATH);
        model = (DefaultTableModel) tblSapXep.getModel();
        diemcuahs = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxMonHoc = new javax.swing.JComboBox<>();
        btnSapxep1 = new javax.swing.JToggleButton();
        btnSapXep2 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSapXep = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnXuatFile = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sắp xếp học sinh theo điểm số");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 653, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel2.setText("Sắp Xếp Theo Điểm Trung Bình Môn:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("Sắp Xếp Theo Điểm Của Môn Học:");

        cbxMonHoc.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        cbxMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toán", "Vật Lý", "Hoá Học", "Sinh Học", "Tin Học", "Công Nghệ", "Ngữ Văn", "Địa Lý", "Lịch Sử", "Giáo Dục Công Dân" }));

        btnSapxep1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnSapxep1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/actvn/quanlysv/images/Statistics.png"))); // NOI18N
        btnSapxep1.setText("Sắp Xếp");
        btnSapxep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapxep1ActionPerformed(evt);
            }
        });

        btnSapXep2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnSapXep2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/actvn/quanlysv/images/Statistics.png"))); // NOI18N
        btnSapXep2.setText("Sắp Xếp");
        btnSapXep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXep2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btnSapXep2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSapxep1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(134, 134, 134))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSapxep1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxMonHoc)
                            .addComponent(btnSapXep2))
                        .addGap(6, 6, 6)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, -1, -1));

        tblSapXep.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tblSapXep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HS", "Toán", "Vật Lý", "Hoá Học", "Sinh Học", "Tin Học", "Công Nghệ", "Ngữ Văn", "Địa Lý", "Lịch Sử", "Giáo Dục Công Dân", "Điểm Trung Bình", "Xếp Loại"
            }
        ));
        jScrollPane1.setViewportView(tblSapXep);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 216, 653, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnXuatFile.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnXuatFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/actvn/quanlysv/images/Save.png"))); // NOI18N
        btnXuatFile.setText("Xuất File JSON");
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(btnXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(btnXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 649, 647, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void fillTable(List<DiemCuaHS> subList) {
        for (DiemCuaHS item : subList) {
            DiemCuaHS hs = item;
            model.addRow(new Object[]{
                hs.getMaHS(),
                hs.getTatCaMon().get(0).getDiem_cac_mon(),
                hs.getTatCaMon().get(1).getDiem_cac_mon(),
                hs.getTatCaMon().get(2).getDiem_cac_mon(),
                hs.getTatCaMon().get(3).getDiem_cac_mon(),
                hs.getTatCaMon().get(4).getDiem_cac_mon(),
                hs.getTatCaMon().get(5).getDiem_cac_mon(),
                hs.getTatCaMon().get(6).getDiem_cac_mon(),
                hs.getTatCaMon().get(7).getDiem_cac_mon(),
                hs.getTatCaMon().get(8).getDiem_cac_mon(),
                hs.getTatCaMon().get(9).getDiem_cac_mon(),
                hs.getDiemTBmon(),
                hs.getHocLuc(),});
        }
    }

    private void btnSapxep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapxep1ActionPerformed
        model.setRowCount(0);
        subList = DiemCuaHSController.compareSubject(data, 10);
        fillTable(subList);
    }//GEN-LAST:event_btnSapxep1ActionPerformed

    private void btnSapXep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXep2ActionPerformed
        model.setRowCount(0);
        subList = new ArrayList<>();
        switch (cbxMonHoc.getSelectedItem().toString()) {
            case "Toán" ->
                subList = DiemCuaHSController.compareSubject(data, 0);
            case "Vật Lý" ->
                subList = DiemCuaHSController.compareSubject(data, 1);
            case "Hoá Học" ->
                subList = DiemCuaHSController.compareSubject(data, 2);
            case "Sinh Học" ->
                subList = DiemCuaHSController.compareSubject(data, 3);
            case "Tin Học" ->
                subList = DiemCuaHSController.compareSubject(data, 4);
            case "Công Nghệ" ->
                subList = DiemCuaHSController.compareSubject(data, 5);
            case "Ngữ Văn" ->
                subList = DiemCuaHSController.compareSubject(data, 6);
            case "Địa Lý" ->
                subList = DiemCuaHSController.compareSubject(data, 7);
            case "Lịch Sử" ->
                subList = DiemCuaHSController.compareSubject(data, 8);
            case "Giáo Dục Công Dân" ->
                subList = DiemCuaHSController.compareSubject(data, 9);
        }
        fillTable(subList);
    }//GEN-LAST:event_btnSapXep2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        NhapDiemChoHocSinhForm loc = new NhapDiemChoHocSinhForm();
        loc.setVisible(true);
        this.setVisible(false);
        loc.pack();
        loc.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowClosing

    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        FileControl.writeJSONFile(subList, com.actvn.qldiemhsthpt.util.FileControl.JSON_SORT_PATH);
    }//GEN-LAST:event_btnXuatFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SapXepDiemHSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SapXepDiemHSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SapXepDiemHSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SapXepDiemHSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SapXepDiemHSForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSapXep2;
    private javax.swing.JToggleButton btnSapxep1;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JComboBox<String> cbxMonHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSapXep;
    // End of variables declaration//GEN-END:variables
}
